--CREACIÓN DEL MODELO DE DATOS
CREATE DATABASE TaskManagerDB;
GO

USE TaskManagerDB;
GO

-- USERS
CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE
);
GO

-- TASKS
CREATE TABLE Tasks (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    UserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),

    -- JSON FIELD
    ExtraData NVARCHAR(MAX),

    CONSTRAINT FK_Tasks_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

-- INDEX
CREATE INDEX IX_Tasks_UserId ON Tasks(UserId);
GO

-- VALIDACIÓN JSON
ALTER TABLE Tasks
ADD CONSTRAINT CK_Tasks_ExtraData_JSON
CHECK (ExtraData IS NULL OR ISJSON(ExtraData) = 1);